name = "consumer"
version = "0.0.1"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "consumer"]

[setting.change_greeting2]
defaultValue = "new greeting!"

[import.greeters]
source = "@ipfs:QmQyz2rwU8vgTtSzfCcB4wx61MWzBLoSeq8JCcgaDjC9Sg"

[import.more_greeters]
source = "greeter:<%= package.version %>"
options.salt = "second"
options.msg = "a message from second greeter set"

[invoke.change_greeting2]
target = ["greeters.greeter"]
func = "setGreeting"
args = ["<%= settings.change_greeting2 %>"]
depends = ["import.greeters"]

# test for factory functionality
[invoke.clone]
target = ["greeters.greeter"]
func = "doCloning"
depends = ["import.greeters"]

factory.cloned.event = "NewClonedGreeter"
factory.cloned.arg = 0
factory.cloned.artifact = "Greeter"
