include = ["cannonfile.toml", "cannonfile.subscription.toml"]

[setting.initialOwner]
defaultValue = "0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"

[setting.l1ChainId]
defaultValue = "11155111"

[setting.optimismL1Sender]
defaultValue = "0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef"

[setting.optimismL2Receiver]
defaultValue = "0x4200000000000000000000000000000000000007"

[setting.subscriptionToken]
defaultValue = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
