name: Build Docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Schema changes
        id: file-changes
        uses: tj-actions/changed-files@v37
        with:
          since_last_remote_commit: true
          files_yaml: |
            schemas:
              - 'packages/builder/src/schemas.zod.ts'
              - 'packages/cli/src/schemas.zod.ts'

      - name: Set up Node
        if: ${{ steps.file-changes.outputs.schemas_any_changed }}
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.1'
      - name: Build Dependencies
        if: ${{ steps.file-changes.outputs.schemas_any_changed }}
        run: |
          npm ci
          npm run build:ts

      - name: Build docs
        if: ${{ steps.file-changes.outputs.schemas_any_changed }}
        run: npm run docgen
